/**
 * STL Import and Export utilities
 */

import * as THREE from 'three';
import { STLLoader } from 'three/addons/loaders/STLLoader.js';
import JSZip from 'jszip';

/**
 * Parse an STL file (binary or ASCII) and return a BufferGeometry
 */
export function parseSTL(buffer: ArrayBuffer): THREE.BufferGeometry {
  const loader = new STLLoader();
  const geometry = loader.parse(buffer);

  // Compute bounding box
  geometry.computeBoundingBox();
  geometry.computeVertexNormals();

  return geometry;
}

/**
 * Get model dimensions from geometry
 */
export function getModelDimensions(geometry: THREE.BufferGeometry): {
  width: number;
  height: number;
  depth: number;
  minX: number;
  maxX: number;
  minY: number;
  maxY: number;
  minZ: number;
  maxZ: number;
  centerX: number;
  centerY: number;
  centerZ: number;
} {
  if (!geometry.boundingBox) {
    geometry.computeBoundingBox();
  }
  const bb = geometry.boundingBox!;

  return {
    width: bb.max.x - bb.min.x,
    height: bb.max.z - bb.min.z, // Z is up in 3D printing
    depth: bb.max.y - bb.min.y,
    minX: bb.min.x,
    maxX: bb.max.x,
    minY: bb.min.y,
    maxY: bb.max.y,
    minZ: bb.min.z,
    maxZ: bb.max.z,
    centerX: (bb.min.x + bb.max.x) / 2,
    centerY: (bb.min.y + bb.max.y) / 2,
    centerZ: (bb.min.z + bb.max.z) / 2,
  };
}

/**
 * Export mesh data to binary STL format
 */
export function exportSTL(
  positions: Float32Array,
  indices: Uint32Array
): ArrayBuffer {
  const numTriangles = indices.length / 3;
  // STL binary format: 80 byte header + 4 byte tri count + 50 bytes per triangle
  const bufferSize = 80 + 4 + numTriangles * 50;
  const buffer = new ArrayBuffer(bufferSize);
  const view = new DataView(buffer);

  // Header (80 bytes) - just zeros/text
  const header = 'Binary STL generated by Gridfinity Base Adder';
  for (let i = 0; i < Math.min(header.length, 80); i++) {
    view.setUint8(i, header.charCodeAt(i));
  }

  // Number of triangles
  view.setUint32(80, numTriangles, true);

  let offset = 84;
  for (let t = 0; t < numTriangles; t++) {
    const i0 = indices[t * 3];
    const i1 = indices[t * 3 + 1];
    const i2 = indices[t * 3 + 2];

    // Get vertices
    const ax = positions[i0 * 3],
      ay = positions[i0 * 3 + 1],
      az = positions[i0 * 3 + 2];
    const bx = positions[i1 * 3],
      by = positions[i1 * 3 + 1],
      bz = positions[i1 * 3 + 2];
    const cx = positions[i2 * 3],
      cy = positions[i2 * 3 + 1],
      cz = positions[i2 * 3 + 2];

    // Compute normal (cross product of edges)
    const e1x = bx - ax,
      e1y = by - ay,
      e1z = bz - az;
    const e2x = cx - ax,
      e2y = cy - ay,
      e2z = cz - az;
    let nx = e1y * e2z - e1z * e2y;
    let ny = e1z * e2x - e1x * e2z;
    let nz = e1x * e2y - e1y * e2x;
    const len = Math.sqrt(nx * nx + ny * ny + nz * nz);
    if (len > 0) {
      nx /= len;
      ny /= len;
      nz /= len;
    }

    // Normal
    view.setFloat32(offset, nx, true);
    offset += 4;
    view.setFloat32(offset, ny, true);
    offset += 4;
    view.setFloat32(offset, nz, true);
    offset += 4;

    // Vertex 1
    view.setFloat32(offset, ax, true);
    offset += 4;
    view.setFloat32(offset, ay, true);
    offset += 4;
    view.setFloat32(offset, az, true);
    offset += 4;

    // Vertex 2
    view.setFloat32(offset, bx, true);
    offset += 4;
    view.setFloat32(offset, by, true);
    offset += 4;
    view.setFloat32(offset, bz, true);
    offset += 4;

    // Vertex 3
    view.setFloat32(offset, cx, true);
    offset += 4;
    view.setFloat32(offset, cy, true);
    offset += 4;
    view.setFloat32(offset, cz, true);
    offset += 4;

    // Attribute byte count (unused)
    view.setUint16(offset, 0, true);
    offset += 2;
  }

  return buffer;
}

/**
 * Export mesh data to 3MF format and trigger download
 */
export async function export3MF(
  positions: Float32Array,
  indices: Uint32Array,
  filename: string
): Promise<void> {
  const numVertices = positions.length / 3;
  const numTriangles = indices.length / 3;

  // Build vertices XML
  let verticesXml = '';
  for (let i = 0; i < numVertices; i++) {
    const x = positions[i * 3];
    const y = positions[i * 3 + 1];
    const z = positions[i * 3 + 2];
    verticesXml += `        <vertex x="${x}" y="${y}" z="${z}"/>\n`;
  }

  // Build triangles XML
  let trianglesXml = '';
  for (let t = 0; t < numTriangles; t++) {
    const v1 = indices[t * 3];
    const v2 = indices[t * 3 + 1];
    const v3 = indices[t * 3 + 2];
    trianglesXml += `        <triangle v1="${v1}" v2="${v2}" v3="${v3}"/>\n`;
  }

  const modelXml = `<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">
  <resources>
    <object id="1" type="model">
      <mesh>
        <vertices>
${verticesXml.trimEnd()}
        </vertices>
        <triangles>
${trianglesXml.trimEnd()}
        </triangles>
      </mesh>
    </object>
  </resources>
  <build>
    <item objectid="1"/>
  </build>
</model>`;

  const contentTypesXml = `<?xml version="1.0" encoding="UTF-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>
</Types>`;

  const relsXml = `<?xml version="1.0" encoding="UTF-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Target="/3D/3Dmodel.model" Id="rel0" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/>
</Relationships>`;

  const zip = new JSZip();
  zip.file('[Content_Types].xml', contentTypesXml);
  zip.folder('_rels')!.file('.rels', relsXml);
  zip.folder('3D')!.file('3Dmodel.model', modelXml);

  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * Parse a 3MF file and return raw mesh data
 */
export async function parse3MF(
  buffer: ArrayBuffer
): Promise<{ positions: Float32Array; indices: Uint32Array }> {
  const zip = await JSZip.loadAsync(buffer);

  const modelFile = zip.file('3D/3Dmodel.model');
  if (!modelFile) {
    throw new Error('Invalid 3MF: missing 3D/3Dmodel.model');
  }

  const modelText = await modelFile.async('text');
  const parser = new DOMParser();
  const doc = parser.parseFromString(modelText, 'application/xml');

  const parserError = doc.querySelector('parsererror');
  if (parserError) {
    throw new Error('Invalid 3MF: malformed XML');
  }

  const vertexEls = doc.querySelectorAll('mesh > vertices > vertex');
  const triangleEls = doc.querySelectorAll('mesh > triangles > triangle');

  const positions = new Float32Array(vertexEls.length * 3);
  for (let i = 0; i < vertexEls.length; i++) {
    positions[i * 3] = parseFloat(vertexEls[i].getAttribute('x') ?? '0');
    positions[i * 3 + 1] = parseFloat(vertexEls[i].getAttribute('y') ?? '0');
    positions[i * 3 + 2] = parseFloat(vertexEls[i].getAttribute('z') ?? '0');
  }

  const indices = new Uint32Array(triangleEls.length * 3);
  for (let t = 0; t < triangleEls.length; t++) {
    indices[t * 3] = parseInt(triangleEls[t].getAttribute('v1') ?? '0', 10);
    indices[t * 3 + 1] = parseInt(triangleEls[t].getAttribute('v2') ?? '0', 10);
    indices[t * 3 + 2] = parseInt(triangleEls[t].getAttribute('v3') ?? '0', 10);
  }

  return { positions, indices };
}

/**
 * Trigger download of an ArrayBuffer as a file
 */
export function downloadSTL(buffer: ArrayBuffer, filename: string): void {
  const blob = new Blob([buffer], { type: 'application/octet-stream' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
